Repository Team-BrewBuds/BE_REPO, pull requests merged in 2024-10, with the labels that each got.

#12 7 게시글 시음기록 댓글 기능
  records/admin.py
  records/migrations/0001_initial.py
  records/models.py
  records/serializers.py
  records/services.py
  records/urls.py
  records/views.py
  tests/commnets_tests.py
  tests/conftest.py
  tests/like_tests.py
  tests/records_tests.py
Labels: ✨ Feature

#13 7 댓글 좋아요 기능
  records/views.py
  tests/like_tests.py
Labels: ✨ Feature

#14 8 기록 저장
  records/admin.py
  records/managers.py
  records/migrations/0001_initial.py
  records/models.py
  records/serializers.py
  records/urls.py
  records/views.py
  tests/conftest.py
  tests/note_tests.py
Labels: ✨ Feature

#17 15 홈 전체 피드 조회
  common/view_counter.py
  config/settings.py
  profiles/managers.py
  profiles/migrations/0002_relationship.py
  profiles/models.py
  pytest.ini
  records/posts/views.py
  records/serializers.py
  records/services.py
  records/tasted_record/views.py
  records/urls.py
  records/views.py
  tests/conftest.py
  tests/feed_tests.py
  tests/records_tests.py
Labels: ✨ Feature

#19 18 인기 게시글
  repo/records/managers.py
  repo/records/migrations/0002_alter_post_subject.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/urls.py
  repo/records/posts/views.py
  tests/conftest.py
  tests/top_posts_tests.py
Labels: ✨ Feature

#22 21 팔로우, 언팔로우 기능
  repo/profiles/managers.py
  repo/profiles/models.py
  repo/profiles/urls.py
  repo/profiles/views.py
  tests/conftest.py
  tests/relationship_tests.py
Labels: ✨ Feature

#23 20 버디 추천
  repo/profiles/helpers.py
  repo/profiles/migrations/0002_userdetail.py
  repo/profiles/models.py
  repo/profiles/serializers.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/managers.py
  tests/budy_recommend_tests.py
  tests/conftest.py
  tests/top_posts_tests.py
Labels: ✨ Feature

#30 Deploy setting branch
  .github/workflows/deploy.yml
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  config/settings/__init__.py
  config/settings/_base.py
  config/settings/dev.py
  config/settings/prod.py
  config/urls.py
  config/wsgi/__init__.py
  config/wsgi/dev.py
  config/wsgi/prod.py
  docker-compose.yml
  docker/Dockerfile
  docker/docker-compose.prod.yaml
  docker/docker-compose.yaml
  docker/prod.Dockerfile
  manage.py
  nginx/Dockerfile
  nginx/nginx.conf
  poetry.lock
  pyproject.toml
  pytest.ini
  repo/beans/migrations/0001_initial.py
  repo/common/utils.py
  repo/common/view_counter.py
  repo/profiles/managers.py
  repo/profiles/migrations/0001_initial.py
  repo/profiles/migrations/0002_userdetail.py
  repo/profiles/migrations/0003_alter_userdetail_coffee_life_and_more.py
  repo/profiles/models.py
  repo/profiles/serializers.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/admin.py
  repo/records/managers.py
  repo/records/migrations/0001_initial.py
  repo/records/migrations/0002_alter_post_subject.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/urls.py
  repo/records/posts/views.py
  repo/records/serializers.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
  scripts/deploy.sh
  scripts/entrypoint.prod.sh
  tests/commnets_tests.py
  tests/conftest.py
  tests/feed_tests.py
Labels: 🌏 Deploy

#36 feat: 애플로그인 방식 커스텀 수정
  config/settings/_base.py
  poetry.lock
  pyproject.toml
  repo/profiles/urls.py
  repo/profiles/views.py
Labels: ✨ Feature

#37 35 시음기록 crud
  repo/beans/migrations/0002_alter_beantastereview_star.py
  repo/beans/models.py
  repo/beans/serializers.py
  repo/beans/urls.py
  repo/beans/views.py
  repo/profiles/managers.py
  repo/profiles/models.py
  repo/profiles/urls.py
  repo/records/migrations/0004_alter_tastedrecord_like_cnt.py
  repo/records/migrations/0005_alter_post_tasted_records.py
  repo/records/migrations/0006_alter_post_tasted_records.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/service.py
  repo/records/tasted_record/urls.py
  repo/records/tasted_record/views.py
Labels: ✨ Feature, 🔨 Refactor

#40 32 게시글 시음기록 댓글 유저 관련 api 오류 수정
  pytest.ini
  repo/beans/migrations/0002_alter_beantastereview_star.py
  repo/beans/models.py
  repo/beans/serializers.py
  repo/beans/urls.py
  repo/beans/views.py
  repo/common/serializers.py
  repo/common/utils.py
  repo/common/view_counter.py
  repo/profiles/managers.py
  repo/profiles/models.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/managers.py
  repo/records/migrations/0003_remove_post_tasted_record_post_tasted_records.py
  repo/records/migrations/0004_alter_tastedrecord_like_cnt.py
  repo/records/migrations/0005_alter_post_tasted_records.py
  repo/records/migrations/0006_alter_post_tasted_records.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/urls.py
  repo/records/posts/views.py
  repo/records/serializers.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/service.py
  repo/records/tasted_record/urls.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
Labels: 📃 Docs, 🐞 BugFix, 🔨 Refactor

#41 홈 기능 구현 서버 배포
  config/settings/_base.py
  poetry.lock
  pyproject.toml
  pytest.ini
  repo/beans/migrations/0002_alter_beantastereview_star.py
  repo/beans/models.py
  repo/beans/serializers.py
  repo/beans/urls.py
  repo/beans/views.py
  repo/common/serializers.py
  repo/common/utils.py
  repo/common/view_counter.py
  repo/profiles/managers.py
  repo/profiles/models.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/managers.py
  repo/records/migrations/0003_remove_post_tasted_record_post_tasted_records.py
  repo/records/migrations/0004_alter_tastedrecord_like_cnt.py
  repo/records/migrations/0005_alter_post_tasted_records.py
  repo/records/migrations/0006_alter_post_tasted_records.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/urls.py
  repo/records/posts/views.py
  repo/records/serializers.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/service.py
  repo/records/tasted_record/urls.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
Labels: 🌏 Deploy

#45 feat : 프로필 기본 정보
  repo/profiles/managers.py
  repo/profiles/serializers.py
  repo/profiles/urls.py
  repo/profiles/views.py
Labels: ✨ Feature

#46 feat : 프로필 편집 기능
  repo/profiles/serializers.py
  repo/profiles/views.py
Labels: ✨ Feature

#48 feat : 팔로우/팔로잉 리스트 기능
  repo/profiles/serializers.py
  repo/profiles/services.py
  repo/profiles/urls.py
  repo/profiles/views.py
Labels: ✨ Feature

#49 25 aws bucket
  config/settings/_base.py
  config/settings/dev.py
  config/settings/prod.py
  poetry.lock
  pyproject.toml
  repo/common/bucket.py
  repo/profiles/migrations/0003_alter_customuser_profile_image.py
  repo/profiles/migrations/0004_merge_20241018_2357.py
  repo/profiles/migrations/0005_alter_relationship_managers.py
  repo/profiles/migrations/0006_alter_customuser_profile_image.py
  repo/profiles/models.py
  repo/records/migrations/0003_alter_photo_photo_url.py
  repo/records/migrations/0007_merge_20241018_2357.py
  repo/records/migrations/0008_alter_photo_photo_url.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/views.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/service.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
Labels: ✨ Feature

#51 8 게시글 시음기록 사진
  config/settings/_base.py
  config/settings/dev.py
  config/settings/prod.py
  poetry.lock
  pyproject.toml
  repo/common/bucket.py
  repo/profiles/migrations/0001_squashed_0006_alter_customuser_profile_image.py
  repo/profiles/migrations/0003_alter_customuser_profile_image.py
  repo/profiles/migrations/0004_merge_20241018_2357.py
  repo/profiles/migrations/0005_alter_relationship_managers.py
  repo/profiles/migrations/0006_alter_customuser_profile_image.py
  repo/profiles/models.py
  repo/records/migrations/0001_squashed_0008_alter_photo_photo_url.py
  repo/records/migrations/0003_alter_photo_photo_url.py
  repo/records/migrations/0007_merge_20241018_2357.py
  repo/records/migrations/0008_alter_photo_photo_url.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/views.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/service.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
Labels: ✨ Feature

#53 52 린팅 포맷팅 수정
  .pre-commit-config.yaml
  config/urls.py
  poetry.lock
  pyproject.toml
  repo/common/view_counter.py
  repo/profiles/migrations/0003_alter_userdetail_coffee_life_and_more.py
  repo/profiles/migrations/0004_alter_customuser_birth_and_more.py
  repo/profiles/models.py
  repo/profiles/serializers.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/recommendation/views.py
  repo/records/posts/views.py
  repo/records/services.py
  repo/records/tasted_record/service.py
  repo/search/views.py
  tests/budy_recommend_tests.py
  tests/commnets_tests.py
  tests/conftest.py
  tests/feed_tests.py
  tests/note_tests.py
  tests/records_tests.py
  tests/relationship_tests.py
  tests/top_posts_tests.py
Labels: ⚙ Setting, 🔨 Refactor

#56 소셜 로그인 + 프로필(일부) 서버 배포
  .pre-commit-config.yaml
  config/settings/_base.py
  config/settings/dev.py
  config/settings/prod.py
  config/urls.py
  poetry.lock
  pyproject.toml
  repo/common/bucket.py
  repo/common/view_counter.py
  repo/profiles/managers.py
  repo/profiles/migrations/0001_squashed_0006_alter_customuser_profile_image.py
  repo/profiles/migrations/0002_userdetail.py
  repo/profiles/migrations/0003_alter_userdetail_coffee_life_and_more.py
  repo/profiles/migrations/0007_alter_customuser_birth_and_more.py
  repo/profiles/models.py
  repo/profiles/serializers.py
  repo/profiles/services.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/recommendation/views.py
  repo/records/migrations/0001_squashed_0008_alter_photo_photo_url.py
  repo/records/migrations/0002_alter_post_subject.py
  repo/records/migrations/0003_remove_post_tasted_record_post_tasted_records.py
  repo/records/migrations/0004_alter_tastedrecord_like_cnt.py
  repo/records/migrations/0005_alter_post_tasted_records.py
  repo/records/migrations/0006_alter_post_tasted_records.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/views.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/service.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
  repo/search/views.py
  tests/budy_recommend_tests.py
  tests/commnets_tests.py
  tests/conftest.py
  tests/feed_tests.py
  tests/note_tests.py
  tests/records_tests.py
  tests/relationship_tests.py
  tests/top_posts_tests.py
Labels: 🌏 Deploy

#58 더미 데이터 생성
  config/settings/_base.py
  poetry.lock
  pyproject.toml
  repo/beans/management/__init__.py
  repo/beans/management/commands/__init__.py
  repo/beans/management/commands/seed_beans.py
  repo/common/management/__init__.py
  repo/common/management/commands/__init__.py
  repo/common/management/commands/seed_all.py
  repo/profiles/management/__init__.py
  repo/profiles/management/commands/__init__.py
  repo/profiles/management/commands/seed_user_and_details.py
  repo/records/management/__init__.py
  repo/records/management/commands/__init__.py
  repo/records/management/commands/seed_comments.py
  repo/records/management/commands/seed_notes.py
  repo/records/management/commands/seed_photos.py
  repo/records/management/commands/seed_posts.py
  repo/records/management/commands/seed_tasted_records.py
Labels: ✅ Test

#62 59 사용자가 작성한 시음기록 리스트 조회
  config/settings/_base.py
  poetry.lock
  pyproject.toml
  repo/common/utils.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/filters.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
Labels: ✨ Feature

#63 60 사용자가 찜한 원두 리스트 조회
  repo/beans/serializers.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/filters.py
  repo/records/services.py
Labels: ✨ Feature

#64 61 사용자 저장한 노트 리스트 조회
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/managers.py
  repo/records/serializers.py
Labels: ✨ Feature

#65 55 사용자가 작성한 게시글 리스트 조회
  config/settings/_base.py
  poetry.lock
  pyproject.toml
  repo/beans/serializers.py
  repo/common/utils.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/filters.py
  repo/records/managers.py
  repo/records/posts/serializers.py
  repo/records/serializers.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
Labels: ✨ Feature

#68 67 spectacular 데코레이터
  repo/beans/schemas.py
  repo/beans/views.py
  repo/profiles/schemas.py
  repo/profiles/views.py
  repo/records/schemas.py
  repo/records/views.py
Labels: 🔨 Refactor

#70 38 홈 전체 게시글 시음기록 feed 리스트 조회 추가 수정
  repo/profiles/views.py
  repo/records/managers.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/views.py
  repo/records/schemas.py
  repo/records/serializers.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
  tests/note_tests.py
Labels: ✨ Feature, 🔨 Refactor

#71 버디 추천 테스트용 데이터, api 수정
  repo/profiles/schemas.py
  repo/profiles/views.py
Labels: ✅ Test

#72 Develop
  config/settings/_base.py
  docker/prod.Dockerfile
  poetry.lock
  pyproject.toml
  repo/beans/management/__init__.py
  repo/beans/management/commands/__init__.py
  repo/beans/management/commands/seed_beans.py
  repo/beans/schemas.py
  repo/beans/serializers.py
  repo/beans/views.py
  repo/common/management/__init__.py
  repo/common/management/commands/__init__.py
  repo/common/management/commands/seed_all.py
  repo/common/utils.py
  repo/profiles/management/__init__.py
  repo/profiles/management/commands/__init__.py
  repo/profiles/management/commands/seed_user_and_details.py
  repo/profiles/schemas.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/filters.py
  repo/records/management/__init__.py
  repo/records/management/commands/__init__.py
  repo/records/management/commands/seed_comments.py
  repo/records/management/commands/seed_notes.py
  repo/records/management/commands/seed_photos.py
  repo/records/management/commands/seed_posts.py
  repo/records/management/commands/seed_tasted_records.py
  repo/records/managers.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/views.py
  repo/records/schemas.py
  repo/records/serializers.py
  repo/records/services.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
  scripts/deploy.sh
  tests/note_tests.py
Labels: 🌏 Deploy

#73 38 홈 전체 게시글 시음기록 (비회원)
  repo/common/utils.py
  repo/records/posts/views.py
  repo/records/schemas.py
  repo/records/services.py
  repo/records/tasted_record/views.py
  repo/records/views.py
Labels: ✨ Feature, 🔨 Refactor

#75 74 게시글 시음기록 댓글 신고
  repo/records/migrations/0009_alter_post_subject_report.py
  repo/records/models.py
  repo/records/schemas.py
  repo/records/serializers.py
  repo/records/services.py
  repo/records/urls.py
  repo/records/views.py
Labels: ✨ Feature

#76 20 버디 추천 비회원
  repo/profiles/schemas.py
  repo/profiles/serializers.py
  repo/profiles/views.py
Labels: 🔨 Refactor
