Repository Team-BrewBuds/BE_REPO, pull requests merged in 2024-12, with the labels that each got.

#107 104 records tasted record service
  repo/profiles/schemas.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/base.py
  repo/records/services.py
  repo/records/tasted_record/schemas.py
  repo/records/tasted_record/service.py
  repo/records/tasted_record/services.py
  repo/records/tasted_record/urls.py
  repo/records/tasted_record/views.py
  tests/profiles/profile_note_tasted_record_tests.py
  tests/records/tasted_record_tests.py
Labels: 🔨 Refactor

#109 104 records feed service
  config/settings/settings_modules/jwt.py
  repo/common/utils.py
  repo/records/managers.py
  repo/records/models.py
  repo/records/posts/services.py
  repo/records/services.py
  repo/records/tasted_record/services.py
  repo/records/views.py
Labels: 🔨 Refactor

#110 104 records service
  config/settings/settings_modules/jwt.py
  repo/common/constants.py
  repo/common/permissions.py
  repo/common/utils.py
  repo/common/view_counter.py
  repo/interactions/like/services.py
  repo/interactions/note/services.py
  repo/profiles/schemas.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/records/base.py
  repo/records/comment/__init__.py
  repo/records/comment/schemas.py
  repo/records/comment/serializers.py
  repo/records/comment/services.py
  repo/records/comment/urls.py
  repo/records/comment/views.py
  repo/records/managers.py
  repo/records/models.py
  repo/records/posts/schemas.py
  repo/records/posts/services.py
  repo/records/posts/urls.py
  repo/records/posts/views.py
  repo/records/schemas.py
  repo/records/serializers.py
  repo/records/services.py
  repo/records/tasted_record/schemas.py
  repo/records/tasted_record/service.py
  repo/records/tasted_record/services.py
  repo/records/tasted_record/urls.py
  repo/records/tasted_record/views.py
  repo/records/urls.py
  repo/records/views.py
  tests/profiles/profile_note_tasted_record_tests.py
  tests/records/comment_tests.py
  tests/records/tasted_record_tests.py
Labels: 🔨 Refactor

#112 97 profiles 유저 도메인 서비스 로직 분리 및 수정
  repo/beans/services.py
  repo/interactions/note/services.py
  repo/interactions/relationship/services.py
  repo/interactions/report/services.py
  repo/profiles/services.py
Labels: 🔨 Refactor

#113 프로필 정보 수정 로직 변경
  repo/profiles/services.py
  repo/profiles/validators.py
Labels: 🐞 BugFix, ✨ Feature

#115 feat: 검색 기능 추가
  config/urls.py
  repo/search/serializers.py
  repo/search/urls.py
  repo/search/views.py
Labels: ✨ Feature

#121 feat: 로그인 - 닉네임 여부 추가
  repo/profiles/urls.py
  repo/profiles/views.py
Labels: 🔨 Refactor
