Repository Team-BrewBuds/BE_REPO, pull requests merged in 2025-04, with the labels that each got.

#191 190 원두랭킹
  config/celery.py
  repo/beans/serializers.py
  repo/beans/services.py
  repo/beans/tasks.py
  repo/beans/urls.py
  repo/beans/views.py
Labels: ✨ Feature

#197 Develop
  repo/beans/migrations/0009_alter_beantastereview_place.py
  repo/beans/models.py
  repo/beans/schemas.py
  repo/beans/services.py
  repo/beans/views.py
  repo/profiles/schemas.py
  repo/profiles/serializers.py
  repo/profiles/services.py
  repo/profiles/urls.py
  repo/profiles/views.py
  repo/search/views.py
Labels: 🌏 Deploy

#198 Set sentry monitering
  .env.example
  config/settings/prod.py
  config/settings/settings_modules/sentry.py
  poetry.lock
  pyproject.toml
Labels: Monitering
