Repository Team-BrewBuds/BE_REPO, pull requests merged in 2025-03, with the labels that each got.

#161 댓글 권한설정 쿼리개선
  repo/records/comment/serializers.py
  repo/records/comment/services.py
  repo/records/comment/views.py
Labels: 🔨 Refactor

#157 156 원두추천
  config/settings/_base.py
  repo/recommendation/apps.py
  repo/recommendation/loaders.py
  repo/recommendation/ml/clustering.ipynb
  repo/recommendation/ml/coffee_beans_info_blend_updated_2.csv
  repo/recommendation/ml/kmeans_model.pkl
  repo/recommendation/ml/mlb_encoder.pkl
  repo/recommendation/ml/recsys_data.csv
  repo/recommendation/views.py
Labels: ✨ Feature

#159 158 계정정보 계정탈퇴
  repo/profiles/models.py
  repo/profiles/schemas.py
  repo/profiles/urls.py
  repo/profiles/views.py
Labels: ✨ Feature

#178 팔로우 저장 여부 정보 추가
  repo/beans/serializers.py
  repo/beans/views.py
  repo/interactions/serializers.py
  repo/profiles/migrations/0010_alter_customuser_gender.py
  repo/records/base.py
  repo/records/posts/serializers.py
  repo/records/posts/services.py
  repo/records/posts/views.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/services.py
  repo/records/tasted_record/views.py
Labels: ✨ Feature

#179 Bean 도메인 관련 api 수정
  repo/beans/migrations/0008_alter_beantaste_bean.py
  repo/beans/models.py
  repo/beans/schemas.py
  repo/beans/serializers.py
  repo/beans/urls.py
  repo/beans/views.py
Labels: 🔨 Refactor

#182 Faet 대댓글 좋아요여부 추가
  repo/records/comment/services.py
  repo/records/comment/views.py
Labels: ✨ Feature, 🔨 Refactor

#183 Develop
  repo/beans/migrations/0008_alter_beantaste_bean.py
  repo/beans/models.py
  repo/beans/schemas.py
  repo/beans/serializers.py
  repo/beans/urls.py
  repo/beans/views.py
  repo/profiles/schemas.py
  repo/profiles/services.py
  repo/records/comment/services.py
  repo/records/comment/views.py
Labels: ✨ Feature, 🔨 Refactor

#184 Fix 원두, 취향리포트 통계 로직 수정
  repo/beans/services.py
  repo/beans/views.py
  repo/profiles/views.py
Labels: 🐞 BugFix, 🔨 Refactor

#185 Refactor 검색 api 로직
  repo/search/filters.py
  repo/search/schemas.py
  repo/search/serializers.py
  repo/search/suggest/__init__.py
  repo/search/suggest/schemas.py
  repo/search/suggest/serializers.py
  repo/search/suggest/urls.py
  repo/search/suggest/views.py
  repo/search/urls.py
  repo/search/views.py
Labels: 🔨 Refactor

#186 Develop
  repo/search/filters.py
  repo/search/schemas.py
  repo/search/serializers.py
  repo/search/suggest/__init__.py
  repo/search/suggest/schemas.py
  repo/search/suggest/serializers.py
  repo/search/suggest/urls.py
  repo/search/suggest/views.py
  repo/search/urls.py
  repo/search/views.py
Labels: 🌏 Deploy

#187 FCM Notification
  .github/workflows/deploy.yml
  .gitignore
  config/settings/_base.py
  config/settings/dev.py
  config/settings/prod.py
  config/urls.py
  poetry.lock
  pyproject.toml
  repo/common/decorators.py
  repo/interactions/like/services.py
  repo/notifications/__init__.py
  repo/notifications/apps.py
  repo/notifications/enums.py
  repo/notifications/message_templates.py
  repo/notifications/migrations/0001_initial.py
  repo/notifications/migrations/__init__.py
  repo/notifications/models.py
  repo/notifications/schemas.py
  repo/notifications/serializers.py
  repo/notifications/services.py
  repo/notifications/signals.py
  repo/notifications/urls.py
  repo/notifications/views.py
  repo/records/tasted_record/services.py
Labels: ✨ Feature

#188 Develop
  .github/workflows/deploy.yml
  .gitignore
  config/settings/_base.py
  config/settings/dev.py
  config/settings/prod.py
  config/urls.py
  poetry.lock
  pyproject.toml
  repo/common/decorators.py
  repo/interactions/like/services.py
  repo/notifications/__init__.py
  repo/notifications/apps.py
  repo/notifications/enums.py
  repo/notifications/message_templates.py
  repo/notifications/migrations/0001_initial.py
  repo/notifications/migrations/__init__.py
  repo/notifications/models.py
  repo/notifications/schemas.py
  repo/notifications/serializers.py
  repo/notifications/services.py
  repo/notifications/signals.py
  repo/notifications/urls.py
  repo/notifications/views.py
  repo/records/tasted_record/services.py
Labels: 🌏 Deploy
