Repository Team-BrewBuds/BE_REPO, pull requests merged in 2025-01, with the labels that each got.

#127 Admin 페이지
  repo/beans/admin.py
  repo/interactions/admin.py
  repo/interactions/report/models.py
  repo/profiles/admin.py
  repo/profiles/models.py
  repo/records/admin.py
Labels: ✨ Feature

#128 Develop
  config/settings/settings_modules/spectacular.py
  repo/beans/admin.py
  repo/interactions/admin.py
  repo/interactions/report/models.py
  repo/profiles/admin.py
  repo/profiles/models.py
  repo/records/admin.py
Labels: 🌏 Deploy

#130 118 검색 상세
  repo/beans/management/commands/seed_official_beans.py
  repo/beans/serializers.py
  repo/beans/urls.py
  repo/beans/views.py
  repo/search/serializers.py
  repo/search/views.py
Labels: ✨ Feature

#131 유저 신고 기능
  repo/interactions/admin.py
  repo/interactions/migrations/0002_rename_report_contentreport_and_more.py
  repo/interactions/report/models.py
  repo/interactions/report/schemas.py
  repo/interactions/report/serializers.py
  repo/interactions/report/services.py
  repo/interactions/report/urls.py
  repo/interactions/report/views.py
Labels: ✨ Feature

#135 원두 도메인 모델 변경
  repo/beans/migrations/0005_alter_beantaste_options_bean_image_url_and_more.py
  repo/beans/models.py
  repo/beans/serializers.py
  repo/beans/views.py
  repo/records/migrations/0011_tastedrecord_tasted_at.py
  repo/records/migrations/0012_alter_tastedrecord_tasted_at.py
  repo/records/models.py
  repo/records/tasted_record/schemas.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/services.py
Labels: 🔨 Refactor

#136 Admin 기능 추가
  config/settings/_base.py
  poetry.lock
  pyproject.toml
  repo/beans/admin.py
  repo/common/admin_filters.py
  repo/common/admin_mixins.py
  repo/interactions/admin.py
  repo/profiles/admin.py
  repo/profiles/models.py
  repo/records/admin.py
  repo/records/models.py
Labels: ✨ Feature

#137 57 더미 데이터 생성
  repo/beans/management/commands/seed_beans.py
  repo/profiles/management/commands/seed_user_and_details.py
  repo/profiles/migrations/0009_alter_customuser_created_at_alter_customuser_email_and_more.py
  repo/records/management/commands/seed_comments.py
  repo/records/management/commands/seed_posts.py
  repo/records/management/commands/seed_tasted_records.py
  repo/records/migrations/0013_alter_post_like_cnt_alter_tastedrecord_like_cnt.py
  repo/records/models.py
Labels: ✨ Feature

#138 원두 기능 추가
  repo/beans/admin.py
  repo/beans/migrations/0006_remove_beantastereview_created_at_and_more.py
  repo/beans/migrations/0007_notusedbean.py
  repo/beans/models.py
  repo/records/migrations/0014_remove_tastedrecord_tasted_at.py
  repo/records/models.py
Labels: ✨ Feature, 🔨 Refactor
