Repository Team-BrewBuds/BE_REPO, pull requests merged in 2025-02, with the labels that each got.

#142 140 검색 수정
  repo/beans/serializers.py
  repo/beans/views.py
  repo/search/serializers.py
  repo/search/views.py
Labels: 🔨 Refactor

#144 Admin report api
  poetry.lock
  pyproject.toml
  repo/common/utils.py
  repo/interactions/report/admin_services.py
  repo/interactions/report/urls.py
  repo/interactions/report/views.py
Labels: ✨ Feature

#145 성능 테스트 및 성능 개선
  .gitignore
  docker-compose.yml
  nginx/Dockerfile
  poetry.lock
  pyproject.toml
  repo/common/utils.py
  repo/interactions/like/services.py
  repo/interactions/relationship/services.py
  repo/interactions/report/admin_services.py
  repo/interactions/report/urls.py
  repo/interactions/report/views.py
  repo/records/base.py
  repo/records/comment/serializers.py
  repo/records/comment/services.py
  repo/records/migrations/0015_post_likes.py
  repo/records/migrations/0016_comment_likes_tastedrecord_likes.py
  repo/records/models.py
  repo/records/posts/serializers.py
  repo/records/posts/services.py
  repo/records/posts/tasks.py
  repo/records/posts/views.py
  repo/records/serializers.py
  repo/records/tasted_record/serializers.py
  repo/records/tasted_record/services.py
  scripts/entrypoint.dev.sh
  tests/locustfile.py
Labels: ✨ Feature, 🔨 Refactor

#147 비회원 피드 조회 캐싱
  repo/records/posts/services.py
  repo/records/posts/views.py
  repo/records/services.py
  repo/records/tasted_record/services.py
  repo/records/tasted_record/views.py
  repo/records/views.py
Labels: 🔨 Refactor

#151 54 원두추천
  repo/recommendation/serializers.py
  repo/recommendation/urls.py
  repo/recommendation/views.py
Labels: ✨ Feature
